### ISSUE TITLE
Segfault on PHP 7.4 with empty array

### ISSUE THREAD

**Issue by zorac** [m6w6/ext-json_post#1]
When using this extension under PHP 7.4, posting a JSON body which decodes to an empty array, eg `[]` (or `{}` when using the default configuration,) triggers a segmentation fault.

I have a PR with a test and possible fix, but I've never previously touched the PHP internals, so I'm not sure how correct it is (or whether it might add a memory leak, etc.)

**Comment by m6w6** [comment]
Thank you for the report! I think I found a proper fix. The issue is that PHP-7.4 optimizes empty arrays, which we didn't account for!

Thanks again!
